frequency: 50

# transform_timeout: 0.01
# transform_time_offset: 0.05

two_d_mode: true
# diagnostics_agg: true

#x     , y     , z,
#roll  , pitch , yaw,
#vx    , vy    , vz,
#vroll , vpitch, vyaw,
#ax    , ay    , az

odom0: /robot_base_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
                true,  true, false,
               false, false, true,
               false, false, false]

imu0: imu_data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false,  true,
              false, false, false]

pose0: amcl_pose
pose0_config: [true,  true,  true,
               true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, false]


publish_tf: true


map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
