local_costmap:
 global_frame: odom
 robot_base_frame: base_footprint
 rolling_window: true

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}

obstacles:
  observation_sources: /pedsim_people_sensor/point_cloud_local /pedsim_obstacle_sensor/point_cloud_local
  /pedsim_people_sensor/point_cloud_local:
    data_type: PointCloud
    sensor_frame: laser_link
    marking: true
    clearing: true
    obstacle_range: 4
    raytrace_range: 4
    map_type: costmap
  /pedsim_obstacle_sensor/point_cloud_local:
    data_type: PointCloud
    sensor_frame: laser_link
    marking: true
    clearing: true
    obstacle_range: 4
    raytrace_range: 4
    map_type: costmap