arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_base_joint
    - shoulder_joint
    - bottom_wrist_joint
    - elbow_joint
    - top_wrist_joint
  gains:
    arm_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bottom_wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    top_wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - wrist_gripper_joint
    - test_link_joint_3
  gains:
    wrist_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    test_link_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1